config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  # home
  get 'home/index'

  # users
  devise_for :users

  # artists
  resources :artists, only: [:index, :show, :create, :destroy]

  # discogs
  get 'discogs/search' => 'discogs#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :name, presence: true
  validates :image_url, presence: true
  validates :discogs_id, presence: true, uniqueness: true

  has_many :subscriptions
  has_many :artists, through: :subscriptions, as: :subscribers

  def discogs_url
    return "https://www.discogs.com/artist/#{discogs_id}"
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  validates :user_id, presence: true
  validates :artist_id, presence: true
  validates :artist_id, uniqueness: { scope: [:user_id, :artist_id] }

  belongs_to :user
  belongs_to :artist
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable

  has_many :subscriptions, dependent: :destroy
  has_many :artists, through: :subscriptions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :discogs_app_name
  def discogs_app_name
    return "AudioLoop/#{Rails.configuration.app_version}"
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_artist, only: [:show, :destroy]

  respond_to :html

  def index
    @artists = Artist.all
    respond_with @artists
  end

  def show
    respond_with @artist
  end

  def create
    @artist = Artist.new(artist_params)
    @artist.save
    redirect_to @artist
  end

  def destroy
    @artist.destroy
    respond_with @artist
  end

  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name, :description, :image_url, :discogs_id)
  end
end

app/controllers/discogs_controller.rb
class DiscogsController < ApplicationController
  before_action :authenticate_user!

  respond_to :html

  def search
    discogs = Discogs::Wrapper.new(discogs_app_name, user_token: ENV['DISCOGS_PERSONAL_TOKEN'])
    search = discogs.search(params[:query], per_page: 10, type: params[:query_type])
    @results = search.results
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_table.html.erb
<div class="table_partial">
  <table id="artists">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Image url</th>
        <th>Discogs ID</th>
        <th colspan="2" width="100"></th>
      </tr>
    </thead>

    <tbody>
      <% artists.each do |artist| %>
        <tr>
          <td><%= artist.name %></td>
          <td><%= artist.description %></td>
          <td><%= link_to 'image', artist.image_url %></td>
          <td><%= link_to artist.discogs_id, artist.discogs_url %></td>
          <td><%= link_to '', artist, class: 'fa fa-eye' %></td>
          <td><%= link_to '', artist, method: :delete, data: { confirm: 'Are you sure?' }, class: 'fa fa-trash' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/artists/index.html.erb
<h1>Artists</h1>

<%= render partial: "artists/table", locals: { artists: @artists } %>

app/views/artists/show.html.erb
<%= render partial: "artists/table", locals: { artists: [@artist] } %>

app/views/discogs/search.html.erb
<h1>Discogs Search Results</h1>

<%= render partial: 'discogs/search_results/artist', collection: @results, as: :result %>

app/views/discogs/search_results/_artist.html.erb
<div class="search-result-artist">
  <p><%= "#{result.title} (#{result.id}) - " %></p>
  <p>
    <%= form_for :artist, url: artists_path, method: :post do |f| %>
      <%= f.hidden_field :name, value: result.title %>
      <%= f.hidden_field :image_url, value: result.cover_image %>
      <%= f.hidden_field :discogs_id, value: result.id.to_i %>
      <%= f.submit 'Add This Artist' %>
    <% end %>
  </p>
</div>

app/views/home/index.html.erb
<h1>Home</h1>
<p>Welcome to AudioLoop.</p>

<h3>Search for an artist:</h3>
<%= form_tag discogs_search_path, method: :get do %>
  <%= label_tag :query, 'Search query:' %>
  <%= text_field_tag :query %>
  <%= hidden_field_tag :query_type, :artist %>
  <%= submit_tag 'Search' %>
<% end %>

app/views/layouts/_dev_header.html.erb
<div class="dev_header"><p>Development Environment</p></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>audioloop</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="site_wrapper">
      <% if Rails.env.development? and ENV['HIDE_DEV_BANNER'] != 'true' %>
        <%= render partial: 'layouts/dev_header' %>
      <% end %>

      <header class="site_header">
        <%= link_to 'audioloop', root_path, class: 'site_logo' %>

        <nav class="site_nav">
          <% if user_signed_in? %>
            <%= link_to 'Artists', artists_path, class: 'site_nav_item' %>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'site_nav_item' %>
          <% else %>
            <%= link_to 'Sign In', new_user_session_path, class: 'site_nav_item' %>
            <%= link_to 'Sign Up', new_user_registration_path, class: 'site_nav_item' %>
          <% end %>
        </nav>
      </header>

      <main class="site_main">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </main>

      <footer class="site_footer">
        <p><%= "AudioLoop v#{Rails.configuration.app_version} &copy;#{Time.zone.now.year} Taylor Thurlow".html_safe %></p>
      </footer>
    </div>
  </body>
</html>